### Server Side Prod ###
FROM node:alpine AS build
WORKDIR /app/client
COPY client/package*.json ./
COPY client ./
RUN npm i -g @angular/cli && npm i
RUN npm run build:ssr
CMD ["node", "dist/app/server/main.js"]
